name: Minify Plugin
permissions:
  contents: write
  pages: write 
on:
  push:
    branches:
    - main
    
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Auto Minify
      uses: nizarmah/auto-minify@latest
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@latest
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
